# This is a GitHub Action workflow to automate the release process.
# For more information about GitHub Actions, see: https://docs.github.com/en/actions

name: Create Release

# Controls when the workflow will run.
on:
  # Triggers the workflow on push events, but only for tags that start with 'v'.
  # For example: v1.0, v1.2.3, v2.0-beta
  push:
    tags:
      - 'v*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  # This workflow contains a single job called "build_and_release".
  build_and_release:
    # The type of runner that the job will run on.
    runs-on: ubuntu-latest
    # Grant permissions for the GITHUB_TOKEN to create a release.
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job.
    steps:
      # Step 1: Check out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Archive the project source code into a zip file.
      # The '--prefix' option ensures all files are inside a top-level directory named 'assistant.koplugin/'.
      - name: Archive project source
        run: |
          git archive -o assistant.koplugin-${GITHUB_REF_NAME#v}.zip --prefix=assistant.koplugin/ ${GITHUB_REF_NAME} \
            ":(exclude).github" \
            ":(exclude).gitignore" \
            ":(exclude).all-contributorsrc"
      
      # Step 2.1: List files in the created zip file for debugging purposes
      - name: List zip file contents
        run: unzip -l assistant.koplugin-${GITHUB_REF_NAME#v}.zip

      # Step 3: Create a GitHub Release and upload the zip file as a release asset.
      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          # Mark this release as a pre-release. Set to 'false' to create a full release.
          prerelease: true
          # The files to upload as release assets.
          files: assistant.koplugin-${{ github.ref_name }}